-- =========================================================================
-- VENTURE ATELIER - DÉPLOIEMENT DU SCHÉMA DE BASE DE DONNÉES ET GESTION ACCÈS SÉCURISÉS (RLS)
-- Devise : "Scaling dreams into dollars"
-- =========================================================================

-- 1. Nettoyage préliminaire
drop table if exists va_users cascade;
drop table if exists va_leads cascade;
drop table if exists va_team cascade;
drop table if exists va_projects cascade;
drop table if exists va_config cascade;

-- Activation de l'extension pgcrypto pour le hachage sécurisé des mots de passe
create extension if not exists pgcrypto;

-- 2. Table des administrateurs authentifiés (Console d'administration)
create table va_users (
    id bigint generated by default as identity primary key,
    email text unique not null,
    password_hash text not null, -- Stocke le hash Blowfish (crypt)
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Insertion de l'administrateur historique par défaut de l'Atelier
-- Identifiants initiaux : ventureatelier@gmail.com / atelier2026
insert into va_users (email, password_hash)
values (
    'ventureatelier@gmail.com',
    crypt('atelier2026', gen_salt('bf', 8))
) on conflict (email) do nothing;

-- 3. Table de configuration globale (Single Row Pattern)
create table va_config (
    id integer primary key default 1 check (id = 1), -- Garantit une ligne unique pour tout le site
    logo_url text,
    background_url text,
    forge_image_url text,
    moon_image_url text,
    light_image_url text,
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Insertion de la configuration par défaut (Vierge ou Initiale)
insert into va_config (id, logo_url, background_url, forge_image_url, moon_image_url, light_image_url)
values (
    1, 
    '', -- No default logo - must be uploaded by the administrator
    'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=1920&q=80', -- Arrière-plan cinématique Moonlight
    '',
    '',
    ''
) on conflict (id) do nothing;

-- 4. Table des projets du Portfolio (CMS)
create table va_projects (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    problem text,
    strategy text,
    deliverables text,
    results text,
    images text,         -- Liste sérialisée en JSON des URLs d'images associées au projet
    updated_at timestamp with time zone default timezone('utc'::text, now()),
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Table des membres de l'équipe (CMS)
create table va_team (
    id bigint generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    role text not null,
    avatar_url text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. Table des leads qualifiés du guide interactif (CRM)
create table va_leads (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    phone text,
    company text,
    project_nature text,
    stage text,
    need text,
    recommendation text,
    status text default 'Nouveau'::text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- =========================================================================
-- ACTIVATION DE LA SÉCURITÉ AU NIVEAU DES LIGNES (ROW LEVEL SECURITY - RLS)
-- =========================================================================

-- Activation du RLS sur chaque table
alter table va_config enable row level security;
alter table va_projects enable row level security;
alter table va_team enable row level security;
alter table va_leads enable row level security;
alter table va_users enable row level security;

-- POLITIQUES POUR VA_CONFIG
-- Lecture autorisée au grand public
create policy "va_config_select_policy" on va_config 
    for select using (true);

-- Modifications (insert/update) réservées EXCLUSIVEMENT aux administrateurs connectés
create policy "va_config_write_policy" on va_config 
    for all 
    using (auth.role() = 'authenticated')
    with check (auth.role() = 'authenticated');

-- POLITIQUES POUR VA_PROJECTS
-- Lecture autorisée au grand public
create policy "va_projects_select_policy" on va_projects 
    for select using (true);

-- Modifications en écriture réservées aux administrateurs connectés
create policy "va_projects_write_policy" on va_projects 
    for all 
    using (auth.role() = 'authenticated')
    with check (auth.role() = 'authenticated');

-- POLITIQUES POUR VA_TEAM
-- Lecture autorisée au grand public
create policy "va_team_select_policy" on va_team 
    for select using (true);

-- Modifications en écriture réservées aux administrateurs connectés
create policy "va_team_write_policy" on va_team 
    for all 
    using (auth.role() = 'authenticated')
    with check (auth.role() = 'authenticated');

-- POLITIQUES POUR VA_LEADS
-- Clients ou leads anonymes peuvent insérer leurs informations
create policy "va_leads_insert_policy" on va_leads 
    for insert with check (true);

-- Seul un administrateur connecté a un droit d'audit ou de modification des leads de projets
create policy "va_leads_admin_policy" on va_leads 
    for all 
    using (auth.role() = 'authenticated')
    with check (auth.role() = 'authenticated');

-- POLITIQUES POUR VA_USERS
-- Table invisible et inaccessible au grand public
create policy "va_users_security_policy" on va_users 
    for all 
    using (auth.role() = 'authenticated')
    with check (auth.role() = 'authenticated');

-- =========================================================================
-- EXPÉDITION DU FLUX EN TEMPS RÉEL (SUPABASE REALTIME)
-- =========================================================================
alter publication supabase_realtime add table va_config;
alter publication supabase_realtime add table va_projects;
alter publication supabase_realtime add table va_team;
alter publication supabase_realtime add table va_leads;

-- =========================================================================
-- SECURE LOGIN RPC FUNCTION (EXPLICIT PASSWORD ENCRYPTION VALIDATION ON SERVER)
-- =========================================================================

create or replace function check_admin_login(p_email text, p_password text)
returns boolean as $$
declare
    v_match boolean;
begin
    select (password_hash = crypt(p_password, password_hash)) into v_match
    from va_users
    where email = p_email;
    return coalesce(v_match, false);
end;
$$ language plpgsql security definer;

-- Grant execution to public so anon user can call it
grant execute on function check_admin_login(text, text) to anon;
grant execute on function check_admin_login(text, text) to authenticated;


-- =========================================================================
-- INITIALISATION DE SUPABASE STORAGE ET POLITIQUES D'ACCÈS
-- =========================================================================

-- 1. Configuration du bucket de stockage d'actifs "venture_atelier"
insert into storage.buckets (id, name, public)
values ('venture_atelier', 'venture_atelier', true)
on conflict (id) do nothing;

-- Nettoyage des politiques existantes pour éviter des erreurs d'initialisation répétée
drop policy if exists "Médiathèque - Lecture publique" on storage.objects;
drop policy if exists "Médiathèque - Téléversement Admin" on storage.objects;
drop policy if exists "Médiathèque - Modification Admin" on storage.objects;
drop policy if exists "Médiathèque - Suppression Admin" on storage.objects;

-- 2. Sécurisation : Politique pour autoriser l'accès en lecture à tout le monde
create policy "Médiathèque - Lecture publique" on storage.objects
    for select using (bucket_id = 'venture_atelier');

-- 3. Sécurisation : Politique pour autoriser aux administrateurs connectés les téléversements
create policy "Médiathèque - Téléversement Admin" on storage.objects
    for insert with check (
        bucket_id = 'venture_atelier' 
        and auth.role() = 'authenticated'
    );

-- 4. Sécurisation : Politique pour autoriser aux administrateurs connectés la modification
create policy "Médiathèque - Modification Admin" on storage.objects
    for update using (
        bucket_id = 'venture_atelier' 
        and auth.role() = 'authenticated'
    );

-- 5. Sécurisation : Politique pour autoriser aux administrateurs connectés la suppression
create policy "Médiathèque - Suppression Admin" on storage.objects
    for delete using (
        bucket_id = 'venture_atelier' 
        and auth.role() = 'authenticated'
    );

-- =========================================================================
-- 6. TABLE DE TRAÇABILITÉ COMPLÈTE ET SÉCURISÉE (JOURNAUX D'AUDIT SÉCURITÉ)
-- =========================================================================

create table if not exists va_audit_logs (
    id bigint generated by default as identity primary key,
    timestamp timestamp with time zone default timezone('utc'::text, now()),
    event_type text not null,          -- AUTH_SUCCESS, AUTH_FAILURE, CONFIG_UPDATE, PROJECT_CREATE, etc.
    actor text not null,               -- 'ventureatelier@gmail.com', 'visiteur', ou 'système'
    description text not null,          -- Détails de l'action effectuée
    ip_address text,                   -- IP de l'utilisateur ou 'Inconnue'
    user_agent text,                   -- User-Agent du navigateur
    status text not null,              -- 'SUCCESS', 'FAILURE', 'WARNING'
    metadata jsonb default '{}'::jsonb  -- Données complémentaires cryptographiques ou payloads de traçabilité
);

-- Activation sécurité au niveau ligne (RLS)
alter table va_audit_logs enable row level security;

-- Nettoyage des politiques existantes pour éviter des erreurs d'initialisation répétée
drop policy if exists "va_audit_logs_insert_policy" on va_audit_logs;
drop policy if exists "va_audit_logs_select_policy" on va_audit_logs;

-- Insertion autorisée sans restrictions pour enregistrer toutes les actions (formulaires, échecs d'auth, etc)
create policy "va_audit_logs_insert_policy" on va_audit_logs 
    for insert with check (true);

-- Lecture réservée exclusivement aux administrateurs d'Atelier connectés
create policy "va_audit_logs_select_policy" on va_audit_logs 
    for select using (auth.role() = 'authenticated');



